---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    pvname: dce-etcd-backup
  name: dce-etcd-backup
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: dce-etcd-backup
    namespace: kube-backup
  nfs:
    server: NFSSERVER
    path: BACKDIR
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: Exists
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
