kind: Deployment
apiVersion: apps/v1
metadata:
  name: dao-2048-dao-2048
  namespace: default
  labels:
    dce.daocloud.io/app: dao-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      dce.daocloud.io/component: dao-2048-dao-2048
  template:
    metadata:
      name: dao-2048-dao-2048
      labels:
        dce.daocloud.io/app: dao-2048
        dce.daocloud.io/component: dao-2048-dao-2048
    spec:
      containers:
        - name: dao-2048-dao-2048
          image: daocloud.io/2048:v1
          resources:
            limits:
              cpu: 128m
              memory: '268435456'
            requests:
              cpu: 64m
              memory: '268435456'
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: dao-2048-test
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
